# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tryVSAppCenter' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tryVSAppCenter

  

  platform :ios, '9.0'
  target 'tryVSAppCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tryVSAppCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tryVSAppCenter-tvOS

  target 'tryVSAppCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
